//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntaCentral.Models
{
    using System;
    using System.Collections.Generic;
    using System.Security.Claims;
    using Microsoft.AspNet.Identity;
    using Microsoft.AspNetCore.Mvc.RazorPages;

    public partial class Publicacion : PageModel
    {
        public int id { get; set; }
        public Nullable<int> Edad { get; set; }
        public byte[] Foto { get; set; }
        public string Ultima_Vista { get; set; }
        public string Descripcion { get; set; }
        public string Comentario { get; set; }
        public string Telefono { get; set; }
        public string Celualar { get; set; }
        public Nullable<System.DateTime> Fecha_Publicacion { get; set; }
        public Nullable<int> User_id { get; set; } 
        public virtual Usuarios Usuarios { get; set; }



    }
}
